language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_script:
  - cd app/client
  - npm install
  - CI=false npm run build
  - cd ../server
  - npm install
  - CI=false npm run build
  - cd ../..
  - cp -r app/server container/server/app
  - cp -r app/client/build container/client
script:
  - docker build -t spikehip/resumake.io-server:latest container/server
  - docker build -t spikehip/resumake.io-client:latest container/client
after_success:
  - if [ "$TRAVIS_BRANCH" == "v3" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push spikehip/resumake.io-server:latest;
    docker push spikehip/resumake.io-client:latest;
    fi
